"""making changes

Revision ID: 04a6ef248538
Revises: 80e0a6cc8866
Create Date: 2023-03-01 10:50:16.942408

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '04a6ef248538'
down_revision = '80e0a6cc8866'
branch_labels = ()
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
