"""making changes

Revision ID: 0cc80215ad9f
Revises: c90ba4d9acad
Create Date: 2023-03-01 16:27:05.695592

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0cc80215ad9f'
down_revision = 'c90ba4d9acad'
branch_labels = ()
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
