"""making changes

Revision ID: 0f90e046afcf
Revises: b20fef443d66
Create Date: 2023-03-01 16:18:30.692759

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0f90e046afcf'
down_revision = 'b20fef443d66'
branch_labels = ()
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
