"""making changes

Revision ID: 137007a57f04
Revises: 8e2cb8aa9e1c
Create Date: 2023-03-01 16:07:47.080061

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '137007a57f04'
down_revision = '8e2cb8aa9e1c'
branch_labels = ()
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
