"""making changes

Revision ID: 1607dc15d29e
Revises: 7c679ad51a54
Create Date: 2023-03-01 10:38:16.690619

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1607dc15d29e'
down_revision = '7c679ad51a54'
branch_labels = ()
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
