"""making changes

Revision ID: 20154bda9fe8
Revises: 334d43fd4b5e
Create Date: 2023-03-01 11:54:25.021307

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '20154bda9fe8'
down_revision = '334d43fd4b5e'
branch_labels = ()
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
