"""making changes

Revision ID: 24a8e4353ac9
Revises: 7c774aa2db01
Create Date: 2023-03-01 12:15:09.529941

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '24a8e4353ac9'
down_revision = '7c774aa2db01'
branch_labels = ()
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
