"""making changes

Revision ID: 251fbfe8e211
Revises: d725b3266293
Create Date: 2023-03-01 12:29:18.959558

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '251fbfe8e211'
down_revision = 'd725b3266293'
branch_labels = ()
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
