"""making changes

Revision ID: 2b50fd194ca8
Revises: 49bbeed4fe45
Create Date: 2023-03-01 11:15:05.176935

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2b50fd194ca8'
down_revision = '49bbeed4fe45'
branch_labels = ()
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
