"""making changes

Revision ID: 30b1257ade65
Revises: 5f9dd9649dac
Create Date: 2023-03-01 11:09:56.865294

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '30b1257ade65'
down_revision = '5f9dd9649dac'
branch_labels = ()
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
