"""making changes

Revision ID: 334d43fd4b5e
Revises: 9e79d2168299
Create Date: 2023-03-01 11:54:23.442516

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '334d43fd4b5e'
down_revision = '9e79d2168299'
branch_labels = ()
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
