"""making changes

Revision ID: 49871524e3f5
Revises: 981d2f3dcebe
Create Date: 2023-03-01 16:31:14.645505

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '49871524e3f5'
down_revision = '981d2f3dcebe'
branch_labels = ()
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
