"""making changes

Revision ID: 49bbeed4fe45
Revises: ff92042e2153
Create Date: 2023-03-01 11:13:18.076234

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '49bbeed4fe45'
down_revision = 'ff92042e2153'
branch_labels = ()
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
