"""making changes

Revision ID: 530edfb4828b
Revises: 6381cb2b1ed4
Create Date: 2023-02-28 18:41:18.681343

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '530edfb4828b'
down_revision = '6381cb2b1ed4'
branch_labels = ()
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
