"""making changes

Revision ID: 550f23e98c74
Revises: 9a1c955333ac
Create Date: 2023-03-01 11:18:34.250886

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '550f23e98c74'
down_revision = '9a1c955333ac'
branch_labels = ()
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
