"""making changes

Revision ID: 5d5333e51b66
Revises: 04a6ef248538
Create Date: 2023-03-01 10:50:18.321046

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5d5333e51b66'
down_revision = '04a6ef248538'
branch_labels = ()
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
