"""making changes

Revision ID: 5de287bbd6a4
Revises: 8fbf0abd5191
Create Date: 2023-03-01 11:26:41.355165

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5de287bbd6a4'
down_revision = '8fbf0abd5191'
branch_labels = ()
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
