"""making changes

Revision ID: 5f9dd9649dac
Revises: f2b1b2f3268d
Create Date: 2023-03-01 11:06:48.360497

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5f9dd9649dac'
down_revision = 'f2b1b2f3268d'
branch_labels = ()
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
