"""making changes

Revision ID: 60275ace8168
Revises: 49871524e3f5
Create Date: 2023-03-01 16:32:57.292513

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '60275ace8168'
down_revision = '49871524e3f5'
branch_labels = ()
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
