"""making changes

Revision ID: 6381cb2b1ed4
Revises: 9e10a794eb0b
Create Date: 2023-02-28 16:04:44.898516

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6381cb2b1ed4'
down_revision = '9e10a794eb0b'
branch_labels = ()
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
