"""making changes

Revision ID: 7093fae434bb
Revises: 24a8e4353ac9
Create Date: 2023-03-01 12:15:11.899956

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7093fae434bb'
down_revision = '24a8e4353ac9'
branch_labels = ()
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
