"""making changes

Revision ID: 70fe50c440a3
Revises: 7543ecb878f5
Create Date: 2023-03-01 10:58:31.836565

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '70fe50c440a3'
down_revision = '7543ecb878f5'
branch_labels = ()
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
