"""making changes

Revision ID: 7543ecb878f5
Revises: d171edf243bc
Create Date: 2023-03-01 10:58:17.389038

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7543ecb878f5'
down_revision = 'd171edf243bc'
branch_labels = ()
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
