"""making changes

Revision ID: 7c774aa2db01
Revises: 20154bda9fe8
Create Date: 2023-03-01 11:55:34.218879

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7c774aa2db01'
down_revision = '20154bda9fe8'
branch_labels = ()
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
