"""making changes

Revision ID: 7f7328ec0c38
Revises: e77f04625d57
Create Date: 2023-03-01 14:29:01.491882

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7f7328ec0c38'
down_revision = 'e77f04625d57'
branch_labels = ()
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
