"""making changes

Revision ID: 80e0a6cc8866
Revises: d945accfb590
Create Date: 2023-03-01 10:49:53.762990

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '80e0a6cc8866'
down_revision = 'd945accfb590'
branch_labels = ()
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
