"""making changes

Revision ID: 81fb6b378a8a
Revises: bd6066f3641d
Create Date: 2023-03-01 10:41:35.181017

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '81fb6b378a8a'
down_revision = 'bd6066f3641d'
branch_labels = ()
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
