"""making changes

Revision ID: 836bc42099f8
Revises: 5de287bbd6a4
Create Date: 2023-03-01 11:35:25.794078

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '836bc42099f8'
down_revision = '5de287bbd6a4'
branch_labels = ()
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
