"""making changes

Revision ID: 85b826d5cd82
Revises: a3e2ed846a6c
Create Date: 2023-03-01 15:48:28.171332

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '85b826d5cd82'
down_revision = 'a3e2ed846a6c'
branch_labels = ()
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
