"""making changes

Revision ID: 8af1db3f859a
Revises: d3238dc3fe35
Create Date: 2023-03-01 11:19:26.583746

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8af1db3f859a'
down_revision = 'd3238dc3fe35'
branch_labels = ()
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
