"""making changes

Revision ID: 8d5c9589d124
Revises: 0cc80215ad9f
Create Date: 2023-03-01 16:27:44.475593

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8d5c9589d124'
down_revision = '0cc80215ad9f'
branch_labels = ()
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
