"""making changes

Revision ID: 8e2cb8aa9e1c
Revises: b4afdb2a0068
Create Date: 2023-03-01 16:06:45.277068

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8e2cb8aa9e1c'
down_revision = 'b4afdb2a0068'
branch_labels = ()
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
