"""making changes

Revision ID: 8fbf0abd5191
Revises: a59859f11f32
Create Date: 2023-03-01 11:26:39.868320

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8fbf0abd5191'
down_revision = 'a59859f11f32'
branch_labels = ()
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
