"""making changes

Revision ID: 91581c6f9403
Revises: 9d8d124f6832
Create Date: 2023-03-01 10:57:46.688790

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '91581c6f9403'
down_revision = '9d8d124f6832'
branch_labels = ()
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
