"""making changes

Revision ID: 943642638d03
Revises: 30b1257ade65
Create Date: 2023-03-01 11:11:33.243396

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '943642638d03'
down_revision = '30b1257ade65'
branch_labels = ()
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
