"""making changes

Revision ID: 981d2f3dcebe
Revises: 8d5c9589d124
Create Date: 2023-03-01 16:31:13.371608

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '981d2f3dcebe'
down_revision = '8d5c9589d124'
branch_labels = ()
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
