"""making changes

Revision ID: 9c41d08e429a
Revises: f661d4f2a112
Create Date: 2023-03-01 11:42:44.131081

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9c41d08e429a'
down_revision = 'f661d4f2a112'
branch_labels = ()
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
