"""making changes

Revision ID: 9d8d124f6832
Revises: e7260c308bb2
Create Date: 2023-03-01 10:57:03.602208

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9d8d124f6832'
down_revision = 'e7260c308bb2'
branch_labels = ()
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
