"""making changes

Revision ID: 9e79d2168299
Revises: de47572932c5
Create Date: 2023-03-01 11:54:05.177245

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9e79d2168299'
down_revision = 'de47572932c5'
branch_labels = ()
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
