"""making changes

Revision ID: a3e2ed846a6c
Revises: 7f7328ec0c38
Create Date: 2023-03-01 14:29:02.869276

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a3e2ed846a6c'
down_revision = '7f7328ec0c38'
branch_labels = ()
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
