"""making changes

Revision ID: a59859f11f32
Revises: 8af1db3f859a
Create Date: 2023-03-01 11:25:31.837540

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a59859f11f32'
down_revision = '8af1db3f859a'
branch_labels = ()
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
