"""making changes

Revision ID: b20fef443d66
Revises: c3c8f05d6f03
Create Date: 2023-03-01 16:18:28.078856

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b20fef443d66'
down_revision = 'c3c8f05d6f03'
branch_labels = ()
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
