"""making changes

Revision ID: b4afdb2a0068
Revises: ff69acb23247
Create Date: 2023-03-01 16:06:43.317020

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b4afdb2a0068'
down_revision = 'ff69acb23247'
branch_labels = ()
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
