"""making changes

Revision ID: bb54abf0f8fe
Revises: c8541028513c
Create Date: 2023-02-27 21:37:42.413658

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'bb54abf0f8fe'
down_revision = 'c8541028513c'
branch_labels = ()
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
