"""making changes

Revision ID: bd6066f3641d
Revises: 1607dc15d29e
Create Date: 2023-03-01 10:41:32.339744

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'bd6066f3641d'
down_revision = '1607dc15d29e'
branch_labels = ()
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
