"""making changes

Revision ID: c2dde7e88efe
Revises: 5d5333e51b66
Create Date: 2023-03-01 10:51:10.305204

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c2dde7e88efe'
down_revision = '5d5333e51b66'
branch_labels = ()
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
