"""making changes

Revision ID: c3c8f05d6f03
Revises: 137007a57f04
Create Date: 2023-03-01 16:07:49.895065

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c3c8f05d6f03'
down_revision = '137007a57f04'
branch_labels = ()
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
