"""making changes

Revision ID: c8541028513c
Revises: 256a0a5bc53c
Create Date: 2023-02-27 21:34:54.312337

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c8541028513c'
down_revision = '256a0a5bc53c'
branch_labels = ()
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
