"""making changes

Revision ID: c90ba4d9acad
Revises: 0f90e046afcf
Create Date: 2023-03-01 16:20:38.020074

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c90ba4d9acad'
down_revision = '0f90e046afcf'
branch_labels = ()
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
