"""making changes

Revision ID: d171edf243bc
Revises: 91581c6f9403
Create Date: 2023-03-01 10:57:48.080991

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd171edf243bc'
down_revision = '91581c6f9403'
branch_labels = ()
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
