"""making changes

Revision ID: d3238dc3fe35
Revises: 550f23e98c74
Create Date: 2023-03-01 11:19:21.345801

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd3238dc3fe35'
down_revision = '550f23e98c74'
branch_labels = ()
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
