"""making changes

Revision ID: d650a6c80114
Revises: 530edfb4828b
Create Date: 2023-02-28 18:41:56.977333

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd650a6c80114'
down_revision = '530edfb4828b'
branch_labels = ()
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
