"""making changes

Revision ID: d6eafb24e2d0
Revises: 7093fae434bb
Create Date: 2023-03-01 12:24:15.639579

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd6eafb24e2d0'
down_revision = '7093fae434bb'
branch_labels = ()
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
