"""making changes

Revision ID: d725b3266293
Revises: d6eafb24e2d0
Create Date: 2023-03-01 12:29:16.525921

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd725b3266293'
down_revision = 'd6eafb24e2d0'
branch_labels = ()
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
