"""making changes

Revision ID: d945accfb590
Revises: 81fb6b378a8a
Create Date: 2023-03-01 10:46:26.129428

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd945accfb590'
down_revision = '81fb6b378a8a'
branch_labels = ()
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
