"""making changes

Revision ID: d9b05877f513
Revises: c2dde7e88efe
Create Date: 2023-03-01 10:51:11.614636

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd9b05877f513'
down_revision = 'c2dde7e88efe'
branch_labels = ()
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
