"""making changes

Revision ID: db50d912423a
Revises: 2b50fd194ca8
Create Date: 2023-03-01 11:15:08.456530

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'db50d912423a'
down_revision = '2b50fd194ca8'
branch_labels = ()
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
