"""making changes

Revision ID: de47572932c5
Revises: 9c41d08e429a
Create Date: 2023-03-01 11:54:03.382393

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'de47572932c5'
down_revision = '9c41d08e429a'
branch_labels = ()
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
