"""making changes

Revision ID: e18cfc0c406d
Revises: 836bc42099f8
Create Date: 2023-03-01 11:36:33.280663

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e18cfc0c406d'
down_revision = '836bc42099f8'
branch_labels = ()
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
