"""making changes

Revision ID: e578887123fe
Revises: 251fbfe8e211
Create Date: 2023-03-01 12:30:41.298364

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e578887123fe'
down_revision = '251fbfe8e211'
branch_labels = ()
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
