"""making changes

Revision ID: e7260c308bb2
Revises: d9b05877f513
Create Date: 2023-03-01 10:57:02.251980

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e7260c308bb2'
down_revision = 'd9b05877f513'
branch_labels = ()
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
