"""making changes

Revision ID: e87e29215e1b
Revises: 85b826d5cd82
Create Date: 2023-03-01 15:48:30.587079

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e87e29215e1b'
down_revision = '85b826d5cd82'
branch_labels = ()
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
