"""making changes

Revision ID: f29615ef8ecd
Revises: bb54abf0f8fe
Create Date: 2023-02-27 21:37:48.285040

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f29615ef8ecd'
down_revision = 'bb54abf0f8fe'
branch_labels = ()
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
