"""making changes

Revision ID: f2b1b2f3268d
Revises: 70fe50c440a3
Create Date: 2023-03-01 11:06:46.996877

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f2b1b2f3268d'
down_revision = '70fe50c440a3'
branch_labels = ()
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
