"""making changes

Revision ID: f661d4f2a112
Revises: e18cfc0c406d
Create Date: 2023-03-01 11:42:42.354679

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f661d4f2a112'
down_revision = 'e18cfc0c406d'
branch_labels = ()
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
