"""making changes

Revision ID: fa721808deec
Revises: e87e29215e1b
Create Date: 2023-03-01 16:04:22.184119

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'fa721808deec'
down_revision = 'e87e29215e1b'
branch_labels = ()
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('telemetryData',
    sa.Column('data_id', postgresql.UUID(as_uuid=True), nullable=False),
    sa.Column('vehicle_id', postgresql.UUID(as_uuid=True), nullable=True),
    sa.Column('data_hora', sa.DateTime(), nullable=True),
    sa.Column('latitude', sa.Float(), nullable=True),
    sa.Column('longitude', sa.Float(), nullable=True),
    sa.Column('altimeter', sa.Integer(), nullable=True),
    sa.Column('telemetry_value', sa.Integer(), nullable=True),
    sa.Column('tipo_sensor', sa.String(length=255), nullable=True),
    sa.PrimaryKeyConstraint('data_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('telemetryData')
    # ### end Alembic commands ###
